name: SSH Access

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH (tmate)
        uses: mxschmitt/action-tmate@v3

      - name: Keep session alive
        run: |
          echo "SSH session is active..."
          sleep 3600
